### ISSUE TITLE
自动重新登陆

### ISSUE THREAD

**Issue by avilliai** [avilliai/Manyana#3]
# 1、修改配置文件
- 记事本打开ManyanLauncher\miraiBot\config\Console\autologin.yml
```
accounts: 
    account: 123456     #123456改成你的机器人账号
    password: 
      kind: PLAIN
      value: pwd          #pwd改成你的机器人密码
    # "protocol": "ANDROID_PHONE" / "ANDROID_PAD" / "ANDROID_WATCH" / "MACOS" / "IPAD"
    # "device": "device.json"
    # "enable": true
    # "heartbeatStrategy": "STAT_HB" / "REGISTER" / "NONE"
    configuration: 
      protocol: ANDROID_PHONE             #推荐改为ANDROID_PAD
      device: device.json
      enable: true
      heartbeatStrategy: STAT_HB
```
- 改完上述三个地方后，从[LauncherUI](https://github.com/avilliai/Manyana/releases/tag/ManyanaUI) 下载最新的launcher并启动即可
